
on:
  workflow_dispatch: { }


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      pull-requests: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven Settings
        uses: s4u/maven-settings-action@v4.0.0
        with:
          servers: |
            [{
              "id": "ossrh",
              "username": "${env.MAVEN_USERNAME}",
              "password": "${env.MAVEN_PASSWORD}"
            },
            {
              "id": "github-snapshots",
              "username": "${env.GITHUB_ACTOR}",
              "password": "${env.GITHUB_TOKEN}"
            },
            {
              "id": "test-fixtures-maven-plugin",
              "username": "${env.GITHUB_ACTOR}",
              "password": "${env.GITHUB_TOKEN}"
            }]

      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
          passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Execute Release
        run: |
          mvn --batch-mode verify \
          -Ppublish-central \
          -Dgpg.passphrase="${GPG_PASSPHRASE}"
          
          find . -name "pom.xml"
          
          cd core/tmp-test-fixtures-deploy
          
          mvn --batch-mode clean deploy \
          -DskipTests \
          -Dmaven.deploy.skip=true \
          -Dgpg.passphrase="${GPG_PASSPHRASE}" \
          -Dgpg.loopback=true

        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}



#      - name: Sync main back to develop
#        run: |
#          git checkout develop
#          git merge -X theirs origin/main --no-ff -m "chore: sync develop with main"
#          git push origin develop
#        env:
#          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
