name: Publish Snapshot to GitHub Packages
on:
  workflow_dispatch: { }
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK with Maven Server Config
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven Settings
        uses: s4u/maven-settings-action@v4.0.0
        with:
          servers: |
            [{
              "id": "github-snapshots",
              "username": "${env.GITHUB_ACTOR}",
              "password": "${env.GITHUB_TOKEN}"
            },{
              "id": "test-fixtures-maven-plugin",
              "username": "${env.GITHUB_ACTOR}",
              "password": "${env.GITHUB_TOKEN}"
            }]

      - name: Build and Deploy
        run: mvn -U -B -ntp -DskipTests=false -DdeployAtEnd=true clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v5
